sdk-v056
evaafi/sdk pull request #12
Opened 2024-09-28 16:25 UTC by iMCrazyDev

2024-09-30 10:20 UTC, masterjedy commented on src/api/math.ts
> +    let gLoanAsset = TON_MAINNET;
Некрасиво использовать реальный ассет для инициализации, потому что совсем не обязательно он в списке loan-ассетов или вообще есть у пользователя. Я бы предложил сделать какой-нибудь UNDEFINED_ASSET, если уж обязательно инициализировать эту переменную конкретным типом.

2024-09-30 10:23 UTC, masterjedy commented on src/api/math.ts
>      let gCollateralValue = 0n;
А можно, пожалуйста, избавиться от префикса g (global в польской нотации...)- он тут совсем не к месту. Я понимаю, что он был в изначальном коде, но это нехорошо.

2024-10-01 13:07 UTC, masterjedy requested changes
Написал замечения.

2024-10-01 13:07 UTC, masterjedy commented on src/contracts/MasterContract.ts
> +    asset: PoolAssetConfig;
Этот ассет все еще дублирует loanAsset.

2024-10-01 13:07 UTC, masterjedy commented on src/contracts/UserContract.ts
> +            tonLiquidation: this._data.liquidationData.greatestLoanAsset === TON_MAINNET,
Я бы все-таки сравнивал по asset_id, потому что сравнивать объекты конечно можно, но не очень безопасно.

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +export function isV5MainPoolConntract(poolConfig: PoolConfig): boolean {
опечатка в имени функции

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
>          minCollateralAmount = (minCollateralAmount * 97n) / 100n;
кстати, я сделал в последней версии 99/100 - вроде работает) хотя сакральный смысл этого мне до сих пор до конца не ясен. возможно это еще и страховка на случай изменения sRate/bRate за несколько секунд пока транзакция

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +    if (collateralAsset !== UNDEFINED_ASSET && totalLimit < totalDebt) {
На будущее, стоит сделать более корректный способ сравнения ассетов, чем сравнивать ссылки на объекты.

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +            (bigIntMax(collateralValue / 2n, bigIntMin(collateralValue, 10_000_000_000n)) *
Насчет этого числа. Это такое пороговое значение, у меня оно равно 100*10^9 - то есть, 100$ (ASSET_PRICE_SCALE). Таким оно было в ликвидаторе до того как я им занялся. Надо уточнить, сколько все-таки там нужно ставить, и вынести в параметр или константу.

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +            (((liquidationAmount * loanAssetPrice * liquidationBonus) / 10000n) * collateralDecimal) /
Вместо этих 10000n следует использовать константу Liquidation Bonus Scale.

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +    const liquidationData = calculateLiquidationData(args.assetsConfig, args.assetsData, args.principals, args.prices, args.poolConfig);
Я бы деструктуризировал параметры из args, тем более, что они и дальше используются. Хотя это вкусовщина конечно.

2024-10-01 13:07 UTC, masterjedy commented on src/api/math.ts
> +        const loanDecimal = 10n ** loanAssetConfig.decimals;
тогда уж loanScale

2024-10-01 13:07 UTC, masterjedy commented on src/constants/assets.ts
> +    jettonMasterAddress: Address.parse('UQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJKZ'),  // fake
стоит вынести в отдельную константу типа NULL_ADDRESS или как-то так

2024-10-01 13:07 UTC, masterjedy commented on src/constants/general.ts
> +export const EVAA_MASTER_TESTNET = Address.parse('EQCoIxsE8m0Q_Ui9uM-2RPtVWXqHK0ttuW2Mccuaj4FfdkLl');  // EQBghPVKxgauOyrcyNYNwE2MRRnebaNpDGpVDQLbml_LIXnK
Какая версия контракта у этого тестнета? Она разве не v6?

2024-10-01 13:29 UTC, iMCrazyDev commented on src/constants/general.ts
> +export const EVAA_MASTER_TESTNET = Address.parse('EQCoIxsE8m0Q_Ui9uM-2RPtVWXqHK0ttuW2Mccuaj4FfdkLl');  // EQBghPVKxgauOyrcyNYNwE2MRRnebaNpDGpVDQLbml_LIXnK
не, это в5 версия, тестнет в6 будет в ветке в6

2024-10-01 13:37 UTC, iMCrazyDev commented on src/api/math.ts
> +    const liquidationData = calculateLiquidationData(args.assetsConfig, args.assetsData, args.principals, args.prices, args.poolConfig);
использовать args попросил Рашид, как основной пользователь этой функции.

2024-10-01 16:03 UTC, iMCrazyDev commented on src/contracts/MasterContract.ts
> +    asset: PoolAssetConfig;
Там есть ликвидейшн бейз, его будем позже перерабатывать и удалим. Я не могу бейз изменить потому что на нем другие функции завязаны. Я хочу отойти от всех грязных бининтов-ассетид

2024-10-01 16:04 UTC, iMCrazyDev commented on src/api/math.ts
>          minCollateralAmount = (minCollateralAmount * 97n) / 100n;
в в6 без магии по-людски реализуем. сейчас что-то менять смысла не вижу

2024-10-01 16:55 UTC, masterjedy commented on src/api/math.ts
> +    const liquidationData = calculateLiquidationData(args.assetsConfig, args.assetsData, args.principals, args.prices, args.poolConfig);
я имел ввиду внутри функции

2024-10-01 17:11 UTC, masterjedy approved these changes

2024-10-02 11:23 UTC, sepezho commented on src/api/parser.ts
> +        if (applyDust && (principal > 0 && (isV5MainPoolContract(poolConfig) ? balance.amount < assetConfig.dust : principal < assetConfig.dust))) {  // v6 will be abs(principals) < dust
рапсиши пж в несколкьо строчек что тут происходит

2024-10-02 11:23 UTC, sepezho commented on src/api/parser.ts
> +        if (applyDust && (principal > 0 && (isV5MainPoolContract(poolConfig) ? balance.amount < assetConfig.dust : principal < assetConfig.dust))) {  // v6 will be abs(principals) < dust
рапсиши пж в несколкьо строчек что тут происходит

2024-10-02 11:23 UTC, sepezho commented on src/api/math.ts
> +            (bigIntMax(collateralValue / 2n, bigIntMin(collateralValue, 10_000_000_000n)) *
в коде ск стоит  100_000_000_000n
думаю надо ставить 100 тут тоже

2024-10-02 14:20 UTC, merged