APP-20 062b feat: fullyParsed, parseUserData without price, Predict APY
evaafi/sdk pull request #22
Opened 2024-12-17 10:23 UTC by iMCrazyDev

2024-12-17 17:53 UTC, sepezho commented on src/api/parser.ts
> +            const totalSupply = BigInt(src.loadUintBig(64));
давай тут LOADINT как в контрактах сделаем
и на тоталбороу

2024-12-18 02:17 UTC, masterjedy requested changes
pls review my comments

2024-12-18 02:17 UTC, masterjedy commented on src/api/parser.ts
> +            const totalSupply = BigInt(src.loadUintBig(64));
Если быть точнее:
s_rate: uint,
b_rate: uint,
total_supply_principal: int,
total_borrow_principal: int,
timestamp: uint,
balance: uint,
tracking_supply_index: uint,
tracking_borrow_index: uint,
awaited_supply: uint

2024-12-18 02:17 UTC, masterjedy commented on src/api/parser.ts
> +        fullyParsed: false,
Что означает этот fullyParsed: false ?

2024-12-18 02:17 UTC, masterjedy commented on package.json
>      "typedoc": "^0.27.4",
с typedoc я бы тоже крышку снял

2024-12-18 02:17 UTC, masterjedy commented on src/api/math.ts
> +
Можно добавить описание функции? aka typedoc

2024-12-18 02:17 UTC, masterjedy commented on src/api/math.ts
> +    if (currentAmount != null && currentAmount != 0n) {
Понимаю, что редкая ситуация, но если repay или withdraw переходит через 0, вероятно надо делить на 2 части.

2024-12-18 02:17 UTC, masterjedy commented on src/api/math.ts
> +export function predictAPY(args: PredictAPYArgs): AssetInterest {
Можно добавить typedoc-описание?

2024-12-18 05:20 UTC, iMCrazyDev commented on src/api/parser.ts
> +        fullyParsed: false,
Может нейминг не очень. Я имел в виду, что если он фалс, то мы userData не полная. Но если говорить конкретно, если нет хотя бы одной цены, то fullyParsed=false

2024-12-18 09:24 UTC, masterjedy commented on src/api/parser.ts
>              buidler.storeUint(src.sRate, 64);
Я думаю стоит сохранять также как большие числа.

2024-12-18 09:27 UTC, masterjedy commented on src/api/parser.ts
>              buidler.storeUint(src.sRate, 64);
Также, я думаю, стоит проинспектировать парсинг/сериализацию AssetConfig.

2024-12-18 09:32 UTC, masterjedy commented on src/api/parser.ts
> +        fullyParsed: false,
я просто пытаюсь понять почему userLiteData всегда !fullyParsed

2024-12-18 09:47 UTC, masterjedy commented on package.json
>      "typedoc": "^0.27.4",
"@orbs-network/ton-access" не используется, по крайней мере, оно закоментировано, использовалось когда-то для тестов.

P.S. я не понимаю, почему текущий вариант разделения на dependencies/devDependancies вообще работает, ведь в dependancies только 2 зависимости, а почти все в dev deps...

Я не уверен, что ^ нужна для     
    "@ton/crypto": "^3.3.0",
    "@tonconnect/sdk": "^3.0.5",
по крайней мере, вряд ли они привилегированнее, чем @ton/core.

я не знаю насчет @types/..., а также ts-node/ts-jest, но с prettier точно стоит крышку снять, потому что либа кажется незначительной, и ее взлом может привлечь меньше внимания. Ну и обновления в crypto-js вряд ли так уж важны - она нужна только в одном месте - при подсчете sha256 для получения id ассетов.

2024-12-18 10:08 UTC, masterjedy commented on src/api/parser.ts
>              buidler.storeUint(src.sRate, 64);
Если что, там все беззнаковые.

2024-12-18 16:01 UTC, merged